### ISSUE TITLE
UTF-8 compatibility fix broke serving filenames with spaces

### ISSUE THREAD

**Issue by MRigal** [johnsensible/django-sendfile#26]
Hi all,

Updating from 0.3.4 to 0.3.6, I had the bad surprise to see that it broke the support of files containing whitespaces.

The response of sendfile 0.3.4 for such a file was :
X-Accel-Redirect: /protected_files/1/files/Backup 2014-09-02-2.sqlbackup
Content-length: 70458
Content-Type: application/octet-stream
Content-Disposition: attachment; filename="Backup 2014-09-02-2.sqlbackup.zip"

And now (since 0.3.5) it is:
X-Accel-Redirect: /protected_files/1/files/Backup%202014-09-02-2.sqlbackup
Content-length: 70458
Content-Type: application/octet-stream
Content-Disposition: attachment; filename="Backup 2014-09-02-2.sqlbackup.zip"

Which makes the download fail...

Best,
Matthieu

**Comment by stevelacey** [comment]
+1 I am also seeing problems with files with spaces

**Comment by johnsensible** [comment]
Any suggestions on how to deal with this?  I'm not 100% sure what needs to be done?

It's been a while since I've done anything on this project.

It actually looks like the latest version doesn't doing any utf8 encoding at all?

https://github.com/johnsensible/django-sendfile/blob/master/sendfile/backends/nginx.py

But I can see in @MRigal example that the filename appears to be URL encoded (e.g. %20 instead of a space).

p.s. sorry for not replying to this sooner.  This ticket appeared one day after the birth of my 2nd child.  Still playing catchup...

**Comment by MRigal** [comment]
OK, I'll try to write a proper test and take a look at that in the next days. It doesn't seem that trivial, especially when willing to have Python 2 and 3 support.

**Comment by johnsensible** [comment]
I've just put a fix in for this.  It's currently just in the master branch.  Am now encoding the filenames to utf8 bytes (as per http://stackoverflow.com/questions/2732268/django-unicode-filenames-with-ascii-headers), rather than using urlquote.

I've updated the tests etc for this, but it would be good if people can actually try this out to make sure it does actually work...

**Comment by johnsensible** [comment]
Once I know it's working I'll package up a new release for PyPi.

**Comment by FreakyDug** [comment]
That fix works for the problem with @s I reported in #35.

**Comment by johnsensible** [comment]
Ok, think I'm just going to package this up and put it on PyPi then.

**Comment by johnsensible** [comment]
Ok 0.3.7 is on PyPi now:

https://pypi.python.org/pypi/django-sendfile/0.3.7
