### ISSUE TITLE
Maintaining the project

### ISSUE THREAD

**Issue by pawelad** [johnsensible/django-sendfile#65]
Hiya @johnsensible,

I found myself using your project in multiple projects and always enjoyed it. As far as I can see (issues, pull requests, stars, etc.) it's still quite popular but from the looks of it, also a bit abandoned. I'd hate to see the project die and would like to offer my help maintaining it, mainly sorting out current issues and pull requests, updating the compatibility/tests to work with new Python/Django versions, etc.

Feel free to have a look at my GitHub profile, where I have a couple of projects with a small userbases that I support. Nothing with the popularity of `django-sendfile` (in terms of stargazers that is ; ) but I am experienced with the 'worklfow' of an open source project, PyPi releases, etc.

Let me know what you think or if you have any questions.

**Comment by mpasternak** [comment]
@johnsensible please pass commit privs to that guy if you don't mind, I'm also interested in this package.

**Comment by mpasternak** [comment]
By the way, @pawelad, check out my branch and my Tox/TravisCI setup. What I am planning to do is to include all the py3k-related patches from current pull requests and make the package support both Python versions and have a decent build system. How about we work on my branch together, I'll give you privs. After some time, if author of original django-sendfile is still silent, we'll fork. What do you say?

**Comment by FMCorz** [comment]
I'd like to find an up-to-date version of this repository as well. I checked yours @mpasternak but I had to debug a fair bit considering that the function now has to be imported from `sendfile.core`.

Would someone dare setting-up a fork (documented), until this repo is updated?

**Comment by timabbott** [comment]
We want to use this in Zulip (https://github.com/zulip/zulip/) and have been blocking on it having a Python 3 support merged for like a year.  I think it's high time to set up a semi-official fork.  I just forked it to https://github.com/zulip/django-sendfile in the Zulip organization and invited you folks to join as write-access collaborators to help things started, but I have no time at all in the next 2 weeks.  

@johnsensible we'd be happy to shut down our fork if you want to start maintaining this again :).

I don't have a ton of time personally, but some other folks from the Zulip project might soon.  I encourage you folks to review and merge PRs there without blocking on me; @adnrs96 is the person in the Zulip project with the most expertise on this.  Let's try to move somewhat cautiously, starting with adding testing infrastructure and then Python 3 support, and having everything be reviewed by someone else from this group; I'd like to avoid breaking things, since it works pretty well as-is.

We'd still need @johnsensible's permission to get the pypi package transferred so that one can do releases, or eventually rename the fork, but we can deal with that once we have something we want to release.  Until then, `pip` supports installing from Git tags.

**Comment by FMCorz** [comment]
@timabbott I think a lot of the work you need has been done by @mpasternak. I have been using it with Python 3. There was a bit of trial and error due to some package structure difference, and perhaps missing dependencies, but all in all it seemed to work. It may perhaps be easier for your team to review the latter instead.

**Comment by timabbott** [comment]
I was actually imagining we'd just grab those changes until you mentioned having to debug a decent amount, so if you're happy with those changes, we can start from there.

I'm also happy to just follow his fork if other folks want to go with that.  I just want to get things unstuck here :)

**Comment by EvaSDK** [comment]
I would really enjoy if all this work was based on top of PR#63 where I tried to keep changes minimal to get to Travis CI integration. PR#66 looks good but it looks like changes are more extensive and it should really strip on the tested Django versions to those actually supported upstream.

**Comment by merwok** [comment]
Is the zulip fork published on PyPI (with an explicit name such as django-sendfile-zulip for the time being)?  That seems like the one missing step here.  Friendly forks can remove pressure on the original author, and other solutions can be done later (merge back, change maintainers, make fork independent).

**Comment by timabbott** [comment]
@merwok not yet, but you can at least now use the GitHub URL in pypi I suppose; I unfortunately got personally a bit swamped just after finding the time to do the fork.  @EvaSDK we'll evaluate the options and consider doing it the other way.  

Pinging @umairwaheed and @adnrs96  from the Zulip project to get their opinions on this, since they're more likely to have time to help.  Can you take a look at #63 and let me know whether you think we should base off that instead?

**Comment by timabbott** [comment]
(I should also note that I'm pretty happy to let other people step up for any and all parts of managing this if someone has the time to commit right now; I just want something to be happening here!)

**Comment by moggers87** [comment]
I've created a fork of this project and uploaded it to pypi: https://pypi.python.org/pypi/django-sendfile2

I've fixed a number of issues with Python 3 and added support for newer versions of Django (from 1.8 to 2.0). Feel free to open bugs and submit PRs for anything I've missed: https://github.com/moggers87/django-sendfile2

**Comment by mpasternak** [comment]
@moggers87 congrats, thanks for stepping up, I'm using your project now. 

@johnsensible thank you very much for the original project and time taken to maintain it. 

EDIT: no longer observing this issue
